# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - healthoneapi

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      API_URL:
        description: 'API URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05F874E9822E4615974202E0576BB80B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60A1BADE860E4DA186486974A9DF642D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2195011DEAF4E68BDEF8AC5572A98A8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'healthoneapi'
          slot-name: 'Production'

      - name: 'Configure App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'healthoneapi'
          app-settings-json: |
            [
              {"name": "AZURE_OPEN_AI_ENDPOINT", "value": "${{ secrets.AZURE_OPEN_AI_ENDPOINT }}"},
              {"name": "AZURE_OPEN_AI_KEY", "value": "${{ secrets.AZURE_OPEN_AI_KEY }}"},
              {"name": "API_VERSION", "value": "${{ secrets.API_VERSION }}"},
              {"name": "DEPLOYMENT_NAME", "value": "${{ secrets.DEPLOYMENT_NAME }}"},
              
              {"name": "COSMOS_DB_URL_APPLICATION", "value": "${{ secrets.COSMOS_DB_URL_APPLICATION }}"},
              {"name": "COSMOS_DB_KEY_APPLICATION", "value": "${{ secrets.COSMOS_DB_KEY_APPLICATION }}"},
              {"name": "DATABASE_NAME_APPLICATION", "value": "${{ secrets.DATABASE_NAME_APPLICATION }}"},
              {"name": "CONTAINER_NAME_APPLICATION", "value": "${{ secrets.CONTAINER_NAME_APPLICATION }}"},
              
              {"name": "COSMOS_DB_URL_FEEDBACK", "value": "${{ secrets.COSMOS_DB_URL_FEEDBACK }}"},
              {"name": "COSMOS_DB_KEY_FEEDBACK", "value": "${{ secrets.COSMOS_DB_KEY_FEEDBACK }}"},
              {"name": "DATABASE_NAME_FEEDBACK", "value": "${{ secrets.DATABASE_NAME_FEEDBACK }}"},
              {"name": "CONTAINER_NAME_FEEDBACK", "value": "${{ secrets.CONTAINER_NAME_FEEDBACK }}"},
              
              {"name": "COSMOS_DB_URL_MHR", "value": "${{ secrets.COSMOS_DB_URL_MHR }}"},
              {"name": "COSMOS_DB_KEY_MHR", "value": "${{ secrets.COSMOS_DB_KEY_MHR }}"},
              {"name": "DATABASE_NAME_MHR", "value": "${{ secrets.DATABASE_NAME_MHR }}"},
              {"name": "CONTAINER_NAME_MHR", "value": "${{ secrets.CONTAINER_NAME_MHR }}"},
              
              { "name": "GITHUB_PAT", "value": "${{ secrets.APP_PAT }}" },
              { "name": "GITHUB_OWNER", "value": "${{ secrets.APP_OWNER }}" },
              
              {"name": "COSMOS_DB_URL_HOSPITAL", "value": "${{ secrets.COSMOS_DB_URL_HOSPITAL }}"},
              {"name": "COSMOS_DB_KEY_HOSPITAL", "value": "${{ secrets.COSMOS_DB_KEY_HOSPITAL }}"},
              {"name": "DATABASE_NAME_HOSPITAL", "value": "${{ secrets.DATABASE_NAME_HOSPITAL }}"},
              {"name": "CONTAINER_NAME_HOSPITAL", "value": "${{ secrets.CONTAINER_NAME_HOSPITAL }}"},
              
              {"name": "DOCUMENT_URL", "value": "${{ secrets.DOCUMENT_URL }}"},
              {"name": "DOCUMENT_KEY", "value": "${{ secrets.DOCUMENT_KEY }}"},
              {"name": "API_URL", "value":"${{ github.event.inputs.API_URL }}"}
            ]
